import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsDeveloper: SidebarsConfig = {
  developerSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsDeveloper;
